---

- name: "Install a specific version of Java"
  yum:
    name: java-1.8.0
    state: present

- name: "Remove the openjdk package"
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: "Install Tomcat 8.x"
  yum:
    pkg: "{{ item }}" 
    state: present
  with_items:
    - tomcat8
    - tomcat8-webapps
    - tomcat8-admin-webapps
    - tomcat8-docs-webapp
  notify: 
    - start tomcat8

- name: "Setup Tomcat8"
  lineinfile:
    path: /etc/tomcat8/tomcat8.conf
    state: present
    line: "{{ item }}"
  with_items:
    - "JAVA_OPTS=\"-Xmx4096m\""
    - "JAVA_OPTS=\"-XX:MaxPermSize=256m\""
  notify:
    - restart tomcat8  

- name: "Forward port 80 to 8080"
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 8080
    comment: Redirect web traffic to port 8080
  become: yes
  notify:
    - restart tomcat8
