---

- name: "start tomcat8"
  service: 
    name: tomcat8
    state: started
    enabled: yes
  notify:
    - start tomcat8

- name: "restart tomcat8"
  service:
    name: tomcat8
    state: restarted
    enabled: yes
  notify:
    - restart tomcat8

